version: '3'
services:
  api:
    container_name: certain-ice-api
    build: ./certain-ice-api
    ports:
      - "3000:3000"
    volumes:
      - ./certain-ice-api:/api
    depends_on:
      - dev-db
    environment:
      RAILS_ENV: 'development'
      DEV_DB_DATABASE: 'certain-ice-dev'
      DEV_DB_USERNAME: dfire
      DEV_DB_PASSWORD: pwd
      DEV_DB_HOST: certain-ice-dev-db
    command:
      /bin/bash -c 'rm /api/tmp/pids/server.pid && rails s -b 0.0.0.0'
  ui:
    container_name: certain-ice-ui
    build: ./certain-ice-ui
    ports:
      - "4200:4200"
    volumes:
      - ./certain-ice-ui:/certain-ice-ui
    depends_on:
      - api
    command:
      /bin/bash -c 'npm install; npm start'
  dev-db:
    container_name: certain-ice-dev-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: db-root-password
      MYSQL_DATABASE: certain-ice-dev
      MYSQL_USER: dfire
      MYSQL_PASSWORD: pwd
    volumes:
      - ./data/database:/var/lib/mysql
    